### ISSUE TITLE
Update LED Case Light Pricing

### ISSUE THREAD

**Issue by LGordonES** [WorldEES/Q#10]
7)	Attached ILT refrigeration LED pricing should be updated in Q.
[ILT LED Lighting Pricelist-PEP-10-1-2016.pdf](https://github.com/WorldEES/Q/files/1432206/ILT.LED.Lighting.Pricelist-PEP-10-1-2016.pdf)

**Comment by LGordonES** [comment]
Need to make sure that we add the stick and driver price together

**Comment by LGordonES** [comment]
@msantange did you send this to us? Can you attach it here?

**Comment by msantange** [comment]
Attached.

**Comment by LGordonES** [comment]
Complete
