### ISSUE TITLE
Add $/kwh & $/therm to Fin-Sum Sheet

### ISSUE THREAD

**Issue by LGordonES** [WorldEES/Q#11]
Would like to have that calculated items added to the fin-sum sheet to give the sales team more insight into our projects. Maybe open up the hidden columns to the left?

**Comment by ZCorso** [comment]
close #11

**Comment by ZCorso** [comment]
This is complete, I can not, for the life of me figure out how to close this issue.

**Comment by LGordonES** [comment]
This is complete
