### ISSUE TITLE
Add Type C T5 Lamp

### ISSUE THREAD

**Issue by LGordonES** [WorldEES/Q#12]
Need to discuss with Gary so we have a price list and a vetted product from the PMs

**Comment by ZCorso** [comment]
I have been working on this. Gary gave me the list of Espen lamps that Kristen approved and I added them into the Fixture Coding Misc and Lighting Budget tabs in the Q3.1a on the P:Drive. Not really sure what to add on the Coding Prop tab like the specific fixtures.

**Comment by LGordonES** [comment]
Let’s take a look at this tomorrow

[cid:image001.jpg@01D336A5.97A36D10]

[cid:image017.png@01D2390B.80565250]



Leanne Gordon / Energy Specialist
Leanne.Gordon@WorldEnergyES.com<mailto:Leanne.Gordon@WorldEnergyES.com> / +1.774.823.4416
World Energy Efficiency Services
Office: +1.774.420.2764 x208 / Fax: +1.774.420.2768
24 Rockdale St, Worcester, MA 01606
www.WorldEnergyES.com<http://www.worldenergyes.com/>



This e-mail is intended only for the named recipient(s) and may contain information that is privileged, confidential and/or exempt from disclosure under applicable law. No waiver of privilege, confidence or otherwise is intended by virtue of communication via the internet. Any unauthorized use, dissemination or copying is strictly prohibited. If you have received this e-mail in error, or are not named as a recipient, please immediately notify the sender and destroy all copies of this e-mail. Thank you.

**Comment by LGordonES** [comment]
@ZCorso I know you have been working on this and we touched base about it yesterday. Now we just have to add the fixtures right?
[Espen Type C pricing 11.6.17.xlsx](https://github.com/WorldEES/Q/files/1476437/Espen.Type.C.pricing.11.6.17.xlsx)

**Comment by ZCorso** [comment]
I sat down with Mike and Gary yesterday, I have to do something with the ballasts and lamps, then yes I have to add the fixtures.

**Comment by LGordonES** [comment]
Ok I’m not sure adding the ballasts is going to be as easy as Mike claims....let me know your thoughts

Sent from iPhone - Please excuse any spelling errors.

Leanne Gordon, BSME
Energy Specialist
CEM - Certified Energy Manager

World Energy Efficiency Services
24 Rockdale St.<x-apple-data-detectors://5/1>
Worcester, MA  01606<x-apple-data-detectors://5/1>
(774) 823-4416 m


On Nov 16, 2017, at 9:12 AM, ZCorso <notifications@github.com<mailto:notifications@github.com>> wrote:


I sat down with Mike and Gary yesterday, I have to do something with the ballasts and lamps, then yes I have to add the fixtures.

**Comment by ZCorso** [comment]
It wasn't... but i figured it out and it all seems good :)

**Comment by LGordonES** [comment]
Ok good

Sent from iPhone - Please excuse any spelling errors.

Leanne Gordon, BSME
Energy Specialist
CEM - Certified Energy Manager

World Energy Efficiency Services
24 Rockdale St.<x-apple-data-detectors://5/1>
Worcester, MA  01606<x-apple-data-detectors://5/1>
(774) 823-4416 m


On Nov 16, 2017, at 2:11 PM, ZCorso <notifications@github.com<mailto:notifications@github.com>> wrote:


It wasn't... but i figured it out and it all seems good :)
