### ISSUE TITLE
Correct Deemed Savings for Prescriptive Gas Measures

### ISSUE THREAD

**Issue by LGordonES** [WorldEES/Q#3]
a.	MA         
    i.	  Aerators – 17 therms or 498 kWh
    ii.	  Shower Heads – 26.5 therms or 777 kWh
    iii.	  Spray Valves – 114 therms or 3,341 kWh
    iv.	  Boiler Reset Controls are now prescriptive, incentivized at 100% - Let’s discuss further.
b.	CT
    i.	 Aerators – 17 therms or 309 kWh
    ii.	 Shower Heads – 26 therms or 475 kWh
    iii.	 Spray Valves – 42 therms or 957 kWh
    iv.	 Boiler Reset Controls – 45 therms

**Comment by ZCorso** [comment]
In progress, made changes, want verification before closing.

**Comment by LGordonES** [comment]
Did we get the info confirmed by Mike?

**Comment by ZCorso** [comment]
Not yet, that’s what I’m waiting for. I think he’ll be in tomorrow, I’ll have him look at it then.

**Comment by LGordonES** [comment]
Ok sounds good

**Comment by LGordonES** [comment]
Mike,

I have the correct prescriptive gas measures for Aerators, Spray Valves, and Showerheads. As for thermostats, I need to find where in the code they are separated by WiFi and Programable, once I do that those will be changed. Same goes for Pipe insulation, as of right now, I don’t know if we separate “Steam” and “Hot Water” pipes (in the code). The Boiler reset controls are not as strait forward as the other measures in the code. I’ll probably need Leanne to take a look at them with me.

Steam Traps and VFD: HVAC Fans are somewhat put into the new Q. I have been adding them into the code where they need to be, but I haven’t created an actual tab/sheet for them. We talked about this briefly on Github, I don’t know which tab/sheet I should mimic, to create them.

Zack



From: Mike Santangelo
Sent: Friday, November 10, 2017 1:55 PM
To: Zach Corso <zach.corso@worldenergyes.com<mailto:zach.corso@worldenergyes.com>>
Cc: Leanne Gordon <leanne.gordon@worldenergyes.com<mailto:leanne.gordon@worldenergyes.com>>
Subject: Prescriptive Gas Measures in MA

Zach,

For our next release, can you please confirm that you have the prescriptive gas measures calculating the savings correctly as seen in the chart below?

[cid:image007.png@01D35A2E.4AFDF870]

I’m not sure if you’ve updated the Programmable Thermostats, Wi-Fi Thermostats or the Pipe Insulation measures, which is why I included the TRM page # to reference the savings algorithms.

Other items:

Boiler Reset Controls: I’m still waiting for the utility to confirm how they’d like us to calculate savings for boiler reset controls. Once I have this info, I’ll forward it over to you. The inputs for this measure will be:


  *   Location
  *   Quantity
  *   System Size (BTU/hr)
  *   System Type (Forced Air, Hot Water or Steam)

This is the pricing matrix for Boiler Reset Controls-

[cid:image008.png@01D35A2E.4AFDF870]


HVAC VFD’s: How are you coming along with adding this measure to Q?


[cid:image001.jpg@01D336A5.97A36D10]

[cid:image017.png@01D2390B.80565250]



Leanne Gordon / Energy Specialist
Leanne.Gordon@WorldEnergyES.com<mailto:Leanne.Gordon@WorldEnergyES.com> / +1.774.823.4416
World Energy Efficiency Services
Office: +1.774.420.2764 x208 / Fax: +1.774.420.2768
24 Rockdale St, Worcester, MA 01606
www.WorldEnergyES.com<http://www.worldenergyes.com/>



This e-mail is intended only for the named recipient(s) and may contain information that is privileged, confidential and/or exempt from disclosure under applicable law. No waiver of privilege, confidence or otherwise is intended by virtue of communication via the internet. Any unauthorized use, dissemination or copying is strictly prohibited. If you have received this e-mail in error, or are not named as a recipient, please immediately notify the sender and destroy all copies of this e-mail. Thank you.
