### ISSUE TITLE
WEQ Labor Rate - Exterior Fixtures

### ISSUE THREAD

**Issue by ZCorso** [WorldEES/Q#37]
I don’t know if this is something on your radar for the next release but figured I’d share if it isn’t.  I just got off the phone with Chris Brennion, and the labor rate for exterior fixtures was changed from $45/ea down to $35/ea.  Here’s what the labor rates should be…

•	0-50 watts - $45/ea
•	51-100 watts - $55/ea
•	101+ watts - $65/ea

**Comment by ZCorso** [comment]
Before I was told to update all exterior fixtures to $45. Do I now go by what Ellie said and change it according to watts?

**Comment by LGordonES** [comment]
I’ll take a look at it and touch base with Liz

Sent from iPhone - Please excuse any spelling errors.

Leanne Gordon, BSME
Energy Specialist
CEM - Certified Energy Manager

World Energy Efficiency Services
24 Rockdale St.<x-apple-data-detectors://5/1>
Worcester, MA  01606<x-apple-data-detectors://5/1>
(774) 823-4416 m


On Jan 5, 2018, at 9:56 AM, ZCorso <notifications@github.com<mailto:notifications@github.com>> wrote:


Before I was told to update all exterior fixtures to $45. Do I now go by what Ellie said and change it according to watts?
