### ISSUE TITLE
Adding New Measure - Steam Traps

### ISSUE THREAD

**Issue by LGordonES** [WorldEES/Q#4]
a.	We need to add Steam Traps as a measure in Q.
   i.	Use 257 therms as the deemed savings.

**Comment by ZCorso** [comment]
When I added the power strips we based it off the hand dryers tab. Do you think there is a tab we can copy and use as a template for this steam trap measure?

**Comment by LGordonES** [comment]
Not sure, it depends on the inputs but I would say it's probably going to be closer to the VFD one or pipe insulation....
@msantange What are the inputs for this going to be?

**Comment by msantange** [comment]
I’m not 100% certain of that answer, but am waiting on a response from Mike Mills.

What I do know is that there are (4) commonly used steam traps and we just need to collect the quantity of each. I believe that’s it.


  *   Float & Thermostatic
  *   Inverted Bucket
  *   Thermodynamic
  *   Thermostatic
