### ISSUE TITLE
Type B Prescriptive CT

### ISSUE THREAD

**Issue by ZCorso** [WorldEES/Q#43]
Making it so in CT when someone uses a Type B lamp, the correct prescriptive price and incentive is used

**Comment by LGordonES** [comment]
Eversource East/West is also changing incentive to $0.20/kwh for Type B lamps

**Comment by ZCorso** [comment]
Idea: Add new column to "Lighting Sum" called "Type". The ES will be able to pick whether the fixture is a type A,B, or C. Depending on that picklist, the material, labor, and incentive will change to fit the type of fixture.

**Comment by ZCorso** [comment]
CT Info


Type A lamps (4’) (fixed pricing)
Mat - $15.00    labor  $5.00    incentive  $5.00

Type B lamps (4’) (fixed pricing)
Mat - $15.00   labor  $10.00   incentive  $5.00

Type B lamps with kit (4’ – 2lamp)
Mat -  $66.67   labor  $44.45   incentive  $44.45

Type B lamps with kit (4’ – 4lamp)
Mat -  $93.02   labor  $62.01   incentive  $62.01

Type B lamps with kit (2’ – 2lamp)
Mat -  $64.79   labor  $43.20   incentive  $43.20

Type B lamps with kit (2’ – 3lamp)
Mat - $76.42   labor   $50.94   incentive  $50.94

Type B lamps with kit (2’ – 4lamp)
Mat - $84.59   labor  $56.39   incentive  $56.39

**Comment by ZCorso** [comment]
Remphos T5 and Phillips T8 = Type A
Fid T8 = Type B

Fixture Coding Prop = Any kits = Kit + lamp price

**Comment by ZCorso** [comment]
Marie was mistaken, kits do not get incentive
