### ISSUE TITLE
Prescriptive Gas 1-Pager

### ISSUE THREAD

**Issue by LGordonES** [WorldEES/Q#5]
Prescriptive Gas 1-Pager for Eversource MA
   a.	I need the attached Prescriptive Gas document auto-populated from the data entered in Q. These 
        measures will be incentivized at 100% in Eversource MA territory.
        i.	This document is subject to change, still finalizing last minute touches and need to get approval 
                from Kristen and Amanda, but I wanted to provide you with the document so you know what to 
                expect.

**Comment by ZCorso** [comment]
[Eversource MA Prescriptive Measures 1-pager 11.22.17.xlsx](https://github.com/WorldEES/Q/files/1535930/Eversource.MA.Prescriptive.Measures.1-pager.11.22.17.xlsx)

**Comment by ZCorso** [comment]
Need clarification and assistance on this one (Friday with Leanne)

**Comment by ZCorso** [comment]
Add page to Q, auto populates... however have to print manually.
