### ISSUE TITLE
Add New Measure - VFD: HVAC Fans

### ISSUE THREAD

**Issue by LGordonES** [WorldEES/Q#8]
a.	Pricing: We have NexRev pricing that can autofill
b.	Savings: We have the deemed savings calcs that we can use.
[Eversource VFD_kWh_savings Calculator.xlsx](https://github.com/WorldEES/Q/files/1432129/Eversource.VFD_kWh_savings.Calculator.xlsx)
[DP Pricing.pdf](https://github.com/WorldEES/Q/files/1432130/DP.Pricing.pdf)

**Comment by ZCorso** [comment]
- Need pricing options and layout for these. (DrivePack explained) *DONE*
- Drop down menus for "RTU fields" and "Phase" field? *DONE*
- Do i add kW savings? *DONE*

**Comment by ZCorso** [comment]
Motor efficiency column added

**Comment by ZCorso** [comment]
Put kW and Kwh formula in code, not in cell *DONE*

**Comment by ZCorso** [comment]
Price for Motors being replaced
Energy Calc for CT
